# Tensor properties - ranks, shapes, and types

## Tensor rank

In [4]:
import tensorflow as tf
tens1 = tf.constant([[[1,2],[2,3]],[[3,4],[5,6]]]) # rank 3 tensor
sess = tf.Session()
print (sess.run(tens1)[1,1,0]) # address an element with t[i,j,k]

5


# Creating new tensors

In [17]:
import tensorflow as tf
import numpy as np
x = tf.constant(np.random.rand(32), dtype = tf.float32) # generate rank 1 tensor which has 32 random numbers
y = tf.constant([1,2,3])

sess = tf.Session()

print(sess.run(x))
print(sess.run(y))

[ 0.06694089  0.40704554  0.07729915  0.08474851  0.68321675  0.96644491
  0.97236317  0.4506973   0.65744954  0.73222774  0.35651681  0.21367987
  0.27190179  0.35362628  0.40827733  0.02435885  0.25420827  0.85115719
  0.66028023  0.69981909  0.08555209  0.18893756  0.06223164  0.78673637
  0.96470618  0.94901669  0.51365107  0.76844889  0.8611604   0.21485953
  0.88984179  0.19638985]
[1 2 3]


## From numpy to tensors and vice versa

### tf.convert_to_tensor

In [23]:
import tensorflow as tf
import numpy as np

sess = tf.Session()

x_data = np.array([[1,2,3],
                   [3,2,6]])

x = tf.convert_to_tensor(x_data, dtype=tf.float32)

print(sess.run(x))
print(x)

[[ 1.  2.  3.]
 [ 3.  2.  6.]]
Tensor("Const_25:0", shape=(2, 3), dtype=float32)


# Graph building

In [25]:
import tensorflow as tf

g = tf.Graph()
with g.as_default():
    
    sess =tf.Session()
    W_m = tf.Variable(tf.zeros([10,5]))
    x_v = tf.placeholder(tf.float32, [None, 10])
    result = tf.matmul(x_v, W_m)
    print (g.as_graph_def())

node {
  name: "zeros"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_FLOAT
        tensor_shape {
          dim {
            size: 10
          }
          dim {
            size: 5
          }
        }
        float_val: 0.0
      }
    }
  }
}
node {
  name: "Variable"
  op: "VariableV2"
  attr {
    key: "container"
    value {
      s: ""
    }
  }
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 10
        }
        dim {
          size: 5
        }
      }
    }
  }
  attr {
    key: "shared_name"
    value {
      s: ""
    }
  }
}
node {
  name: "Variable/Assign"
  op: "Assign"
  input: "Variable"
  input: "zeros"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "_class"
    value {
      list {
        s: "loc:@Variable"
      }
    }
