# Basic RNNs in Tensorflow

In [5]:
import tensorflow as tf
n_inputs = 3
n_neurons = 5

X0 = tf.placeholder(tf.float32, [None, n_inputs])
X1 = tf.placeholder(tf.float32, [None, n_inputs])

Wx = tf.Variable(tf.random_normal(shape=[n_inputs, n_neurons], 
                                  dtype=tf.float32))
Wy = tf.Variable(tf.random_normal(shape=[n_neurons, n_neurons],
                                  dtype=tf.float32))
b = tf.Variable(tf.zeros([1, n_neurons], dtype=tf.float32))

Y0 = tf.tanh(tf.matmul(X0, Wx) + b)
Y1 = tf.tanh(tf.matmul(Y0, Wy) + tf.matmul(X1, Wx) + b)

init = tf.global_variables_initializer()

In [7]:
import numpy as np

# Mini-batch: instance 0, instance 1, instance 2, instance 3
X0_batch = np.array([[0,1,2], [3,4,5], [6,7,8], [9,0,1]]) # t = 0
X1_batch = np.array([[9,8,7], [0,0,0], [6,5,4], [3,2,1]]) # t = 1

with tf.Session() as sess:
    init.run()
    Y0_val, Y1_val = sess.run([Y0, Y1], feed_dict={X0: X0_batch, X1: X1_batch})

In [8]:
print(Y0_val) # output at t = 0

[[ 0.07326558 -0.99998885  0.81455541  0.87243694  0.00757674]
 [-0.04741782 -1.         -0.92534816  0.99999833  0.01807934]
 [-0.16673264 -1.         -0.99969274  1.          0.02857789]
 [ 0.99812913  1.         -1.          1.         -0.9985919 ]]


In [9]:
print(Y1_val)

[[-0.66726637 -1.         -0.99999994  1.         -0.67476475]
 [-0.7039603   0.15950081  0.87068558  0.99776095  0.04765974]
 [-0.8416549  -0.99999517 -0.99995816  1.         -0.09167944]
 [-0.67073494  0.31090888 -0.99794179  0.99999833  0.99910611]]


# Training to Predict Time Series

In [12]:
n_steps = 20
n_inputs = 1
n_neurons = 100
n_outputs = 1

X = tf.placeholder(tf.float32, [None, n_steps, n_inputs])
y = tf.placeholder(tf.float32, [None, n_steps, n_outputs])

cell = tf.contrib.rnn.OutputProjectionWrapper(
    tf.contrib.rnn.BasicRNNCell(num_units=n_neurons, activation=tf.nn.relu),
    output_size=n_outputs)

outputs, states = tf.nn.dynamic_rnn(cell, X, dtype=tf.float32)

In [13]:
learning_rate = 0.001

loss = tf.reduce_mean(tf.square(outputs - y))
optimizer = tf.train.AdamOptimizer(learning_rate=learning_rate)
training_op = optimizer.minimize(loss)

init = tf.global_variables_initializer()

In [ ]:
def fetch_batch(data, epoch, batch_index, batch_size):
    np.random.seed(epoch * n_batches + batch_index)  # not shown in the book
    indices = np.random.randint(m, size=batch_size)  # not shown
    X_batch = data[indices] # not shown
    y_batch = target.reshape(-1, 1)[indices] # not shown
    return X_batch, y_batch

In [14]:
n_iterations = 1500
batch_size = 50

with tf.Session() as sess:
    init.run()
    for iteration in range(n_iterations):
        X_batch, y_batch = # featch the next training batch
        sess.run(training_op, feed_dict={X: X_batch, y: y_batch})
        if iteration % 100 == 0:
            mse = loss.eval(feed_dict={X: X_batch, y: y_batch})
            print(iteration, "\tMSE:", mse)

SyntaxError: invalid syntax (<ipython-input-14-1ca231d7d6a0>, line 7)